#!/bin/bash
echo  "Aguarde..."
cd  ~
# ALTERAR AQUI
cd /www/web/izing/backend
git checkout master
git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
#npx sequelize db:seed
pm2 restart all

echo  "Update finalizado!"
